version: 2
# there is no conda support for dependabot so this is the closest analog
# since the conda deps are also built from pyproject.toml it should work well enough
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
