image: condaforge/mambaforge:latest

before_script:
  - apt-get update -q -y
  - apt-get install -y build-essential
  - apt-get install libgl1-mesa-glx -y
  - mamba env create -f environment.yml
  - source activate pyflwdir
  - pip install -e .
  
tests:
  script:
    - cd tests
    - export NUMBA_DISABLE_JIT=1
    - python -m pytest --verbose --cov=pyflwdir
    - export NUMBA_DISABLE_JIT=0
    - python -m pytest --cache-clear
    - cd ..
    - black --check . 

pages:
  script:
  - cp notebooks/*.ipynb docs/
  - cp notebooks/*.tif docs/
  - cd docs
  - make html
  - cd ..
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
