name: pyflwdir

channels:
  - conda-forge

# note that these are the developer dependencies,
# if you only want the user dependencies, see
# install_requires in setup.py
dependencies:
  - python=3.6
  - numba
  - numpy
  - xarray
  - rasterio
  - geopandas
  - pytest
  - pytest-cov
  - pytest-benchmark
  - sphinx
  - sphinx_rtd_theme
  

