name: pyflwdir

channels:
- conda-forge

dependencies:
- affine
- cartopy>=0.20
- descartes
- geopandas>0.8
- jupyter
- matplotlib
- numba>=0.54,<1.0
- numpy
- pandoc
- python~=3.12.0
- rasterio
- scipy
