name: pyflwdir

channels:
  - conda-forge

# note that these are the developer dependencies,
# if you only want the user dependencies, see
# install_requires in setup.py
dependencies:
  # required
  - python>=3.7
  - pyflwdir
  # optional for notebooks
  - cartopy
  - descartes
  - geopandas
  - jupyter
  - matplotlib
  - rasterio