name: Tests Coverage

on:
  push:
    branches: [main]
    paths:
      - tests/*
      - pyflwdir/*
      - pyproject.toml
  pull_request:
    branches: [main]
    paths:
      - tests/*
      - pyflwdir/*
      - pyproject.toml


jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.python-version }}-${{ github.ref }}
      cancel-in-progress: true
    steps:

      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: "v0.39.2"
          environments: test-py312
          locked: false
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      # run test
      - name: Test
        run: pixi run -e test-py312 test


      # upload coverage
      - uses: codecov/codecov-action@v3
