name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Test:
    name: Test coverage & style
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.11"
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          environment-file: envs/pyflwdir-dev.yml
          activate-environment: pyflwdir-dev

      - name: Test
        run: |
         export NUMBA_DISABLE_JIT=1
         python -m pytest --verbose --cov=pyflwdir --cov-report xml

      - name: Check style
        run: black --check .

      - uses: codecov/codecov-action@v1