name: Tests Coverage

on:
  push:
    branches: [main]
    paths:
      - tests/*
      - pyflwdir/*
      - pyproject.toml
  pull_request:
    branches: [main]
    paths:
      - tests/*
      - pyflwdir/*
      - pyproject.toml


jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.python-version }}-${{ github.ref }}
      cancel-in-progress: true
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        id: pip
        with:
          # caching, see https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: pyproject.toml

      # true if cache-hit occurred on the primary key
      - name: Cache hit
        run: echo '${{ steps.pip.outputs.cache-hit }}'

      # build environment with pip
      - name: Install pyflwdir
        run: |
          pip install --upgrade pip
          pip install .[test]
          pip list

      # run test
      - name: Test
        run: |
          export NUMBA_DISABLE_JIT=1
          python -m pytest --verbose --cov=pyflwdir --cov-report xml

      # upload coverage
      - uses: codecov/codecov-action@v3
